# Generated by Django 2.0.5 on 2018-06-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='id',
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
