# Generated by Django 2.0.5 on 2018-07-05 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insumoapp', '0002_auto_20180628_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaProduto',
            fields=[
                ('codigo', models.AutoField(default=1000000, primary_key=True, serialize=False)),
                ('qtd', models.IntegerField()),
                ('dt_mov', models.DateTimeField(auto_now_add=True)),
                ('entrada', models.CharField(default='entrada', max_length=10)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='insumoapp.Produto')),
            ],
        ),
        migrations.CreateModel(
            name='SaidaProduto',
            fields=[
                ('codigo', models.AutoField(default=2000000, primary_key=True, serialize=False)),
                ('qtd', models.IntegerField()),
                ('dt_mov', models.DateTimeField(auto_now_add=True)),
                ('saida', models.CharField(default='saida', max_length=10)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='insumoapp.Produto')),
            ],
        ),
    ]
