# Generated by Django 2.0.5 on 2018-07-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumoapp', '0004_auto_20180705_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaproduto',
            name='dt_mov',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='saidaproduto',
            name='dt_mov',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
