# Generated by Django 2.0.5 on 2018-07-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumoapp', '0005_auto_20180705_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaproduto',
            name='codigo',
            field=models.BigIntegerField(default=1000000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='saidaproduto',
            name='codigo',
            field=models.BigIntegerField(default=2000000, primary_key=True, serialize=False),
        ),
    ]
