# Generated by Django 2.0.5 on 2018-07-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumoapp', '0007_auto_20180705_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaproduto',
            name='codigo',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='saidaproduto',
            name='codigo',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
