# Generated by Django 2.0.5 on 2018-07-05 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumoapp', '0008_auto_20180705_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entradaproduto',
            old_name='entrada',
            new_name='tip',
        ),
        migrations.RenameField(
            model_name='saidaproduto',
            old_name='saida',
            new_name='tip',
        ),
    ]
